#!/home/user/projects/TQA-MOEX-futures/.venv/bin/python
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import moexalgo
moexalgo.session.TOKEN = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJaVHA2Tjg1ekE4YTBFVDZ5SFBTajJ2V0ZldzNOc2xiSVR2bnVaYWlSNS1NIn0.eyJleHAiOjE4MTI4MDQzMjUsImlhdCI6MTc4MTcwMTc2MCwiYXV0aF90aW1lIjoxNzgxNzAwODkwLCJqdGkiOiJjMmMzMGE4Ni0yYjFiLTQyYzQtYTc2MC02M2Q0MDlhNTgyYzUiLCJpc3MiOiJodHRwczovL3NzbzIubW9leC5jb20vYXV0aC9yZWFsbXMvY3JhbWwiLCJhdWQiOlsiYWNjb3VudCIsImlzcyJdLCJzdWIiOiJmOjBiYTZhOGYwLWMzOGEtNDlkNi1iYTBlLTg1NmYxZmU0YmY3ZToxYWQzMTA5NC02M2U5LTQ2ZDItOGEwZi1mN2FjODNhZDlkYmUiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJpc3MiLCJzaWQiOiI4ODk1NmNhOS02NGU5LTQ3NzUtOWRkNy1lY2JjNWRjZDZhYTEiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIi8qIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIGlzc19hbGdvcGFjayBwcm9maWxlIG9mZmxpbmVfYWNjZXNzIGVtYWlsIGJhY2t3YXJkc19jb21wYXRpYmxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJpc3NfcGVybWlzc2lvbnMiOiIxMzcsIDEzOCwgMTM5LCAxNDAsIDE2NSwgMTY2LCAxNjcsIDE2OCwgMzI5LCA0MjEsNDMwLCA1MDMsIDQ1MywgNTA5IiwibmFtZSI6ItCe0LvQtdCzINCi0LDRgNC80LDQtdCyIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiMWFkMzEwOTQtNjNlOS00NmQyLThhMGYtZjdhYzgzYWQ5ZGJlIiwiZ2l2ZW5fbmFtZSI6ItCe0LvQtdCzIiwic2Vzc2lvbl9zdGF0ZSI6Ijg4OTU2Y2E5LTY0ZTktNDc3NS05ZGQ3LWVjYmM1ZGNkNmFhMSIsImZhbWlseV9uYW1lIjoi0KLQsNGA0LzQsNC10LIifQ.N8yw064fjz0HqQ67yYcIQtShsQvWCNLgAqyLMXZrr-qI3EaB8ttYUNb6QT7zr3TV-zEoEH4V-CCn-wM6e7r1Umbv7fWsWWUetv4WwNAqlGSIoD376czPpHtcWBbdHqU-h0SpbY2TTP-tai73tA67LM0zBcxA8BFFHhil3MCPYFegZbDkCta3lelmnMS6cUeOcvXYkGoXO0h4NwO6P35RJUPDu4Z1wYwKISSlVtPCdImCNV0LzUWEUf182igC2LLkxRKWrTayaoQcFVmnkXuyiCk2keBtztJJOAGWnTkInNhvQ9zPxx3l45yJnd84v3xgd_WrA4UXjSxXUmHLuhQTSA"

from datetime import datetime
today = datetime.now().strftime("%Y-%m-%d")
data = list(moexalgo.Market("forts").tradestats(date=today, native=True))
print(f"Rows: {len(data)}")
if data:
    cols = list(data[0].keys())
    print(f"Columns ({len(cols)}): {cols}")
    r = data[0]
    for k in cols:
        v = r.get(k)
        if v is not None:
            print(f"  {k}: {v}")
